USE [master]
GO

/****** Object:  Database [EventDb]    Script Date: 3/5/2026 12:30:11 AM ******/
CREATE DATABASE [EventDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EventDb', FILENAME = N'C:\Users\Welcome\EventDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EventDb_log', FILENAME = N'C:\Users\Welcome\EventDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EventDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EventDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EventDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EventDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EventDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EventDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [EventDb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [EventDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EventDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EventDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EventDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EventDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EventDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EventDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EventDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EventDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [EventDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EventDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EventDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EventDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EventDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EventDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EventDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EventDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EventDb] SET  MULTI_USER 
GO

ALTER DATABASE [EventDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EventDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EventDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EventDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EventDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EventDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EventDb] SET QUERY_STORE = ON
GO

ALTER DATABASE [EventDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [EventDb] SET  READ_WRITE 
GO

